export enum RECIPE_ACTION_TYPES {
    ADD_RECIPE_START = 'recipe/ADD_RECIPE_START',
    ADD_RECIPE_SUCCESS = 'recipe/ADD_RECIPE_SUCCESS',
    ADD_RECIPE_FAILED = 'recipe/ADD_RECIPE_FAILED',

    GET_RECIPIES_START = 'recipe/GET_RECIPIES_START',
    GET_RECIPIES_SUCCESS = 'recipe/GET_RECIPIES_SUCCESS',
    GET_RECIPIES_FAILED = 'recipe/GET_RECIPIES_FAILED',

    GET_RECIPE_COUNT_START = 'recipe/GET_RECIPE_COUNT_START',
    GET_RECIPE_COUNT_SUCCESS = 'recipe/GET_RECIPE_COUNT_SUCCESS',
    GET_RECIPE_COUNT_FAILED = 'recipe/GET_RECIPE_COUNT_FAILED',
}